### ISSUE TITLE
How can i add Arabic Language ??

### ISSUE THREAD

**Issue by EyadShalabi** [vlomme/Multi-Tacotron-Voice-Cloning#1]
How can i add Arabic Language ??

**Comment by vlomme** [comment]
Replied you by email

**Comment by minghau** [comment]
Same question ... and for Chinese.

**Comment by vlomme** [comment]
https://github.com/vlomme/Multi-Tacotron-Voice-Cloning/wiki/Training-(and-for-other-languages)
or
https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training

**Comment by Aziz87** [comment]
Голос Путина так и не удалось синтезировать)))
Чтоб без запинок
--
Отправлено из Mail.ru для Android вторник, 26 ноября 2019г., 11:20 +03:00 от Kramarenko Vladislav  notifications@github.com :

**Comment by vlomme** [comment]
Для этого надо обучать на большем объёме голосов, или менять подход. Если же нужен только один голос, то есть более простые пути. Мой один из первых голосов https://soundcloud.com/fn5va3vghrkh/putiin
> Голос Путина так и не удалось синтезировать))) Чтоб без запинок

**Comment by Aziz87** [comment]
А модель обученная не завалялась? )


~~~~~~~~~~~~~~~~~~~~~~
Best regards, Aziz Mamoyan

>Вторник, 26 ноября 2019, 16:33 +03:00 от Kramarenko Vladislav <notifications@github.com>:
>
>Для этого надо обучать на большем объёме голосов, или менять подход. Если же нужен только один голос, то есть более простые пути. Мой один из первых голосов  https://soundcloud.com/fn5va3vghrkh/putiin
>>Голос Путина так и не удалось синтезировать))) Чтоб без запинок
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

**Comment by mennatallah644** [comment]
How can i add Arabic Language ??

**Comment by tailname** [comment]
> Для этого надо обучать на большем объёме голосов, или менять подход. Если же нужен только один голос, то есть более простые пути. Мой один из первых голосов https://soundcloud.com/fn5va3vghrkh/putiin
> 
> > Голос Путина так и не удалось синтезировать))) Чтоб без запинок

господи, это идеально на 200% . Почему я не слышал этого раньше ?
