### ISSUE TITLE
No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by afonya01** [vlomme/Multi-Tacotron-Voice-Cloning#10]
Tryed to run google collab, but there is an error. Please help.

How to implement it on local Computer?

**Comment by vlomme** [comment]
fixed

**Comment by afonya01** [comment]
Thank you! It works. But can I get smwhre manual how to implement it as API on local GPU machine?
Thank you in advance!

**Comment by vlomme** [comment]
train https://github.com/vlomme/Multi-Tacotron-Voice-Cloning/wiki/Training-(and-for-other-languages)
use demo_cli.py or demo_toolbox.py

**Comment by afonya01** [comment]
Thanks a lot! Can you share please a contact for questioning with models, etc? I really want to understand with it. Mb telegram, or other.

Thank you!

**Comment by vlomme** [comment]
niw9102@gmail.com

**Comment by afonya01** [comment]
Thank you!
