### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by arahisman** [vlomme/Multi-Tacotron-Voice-Cloning#11]
Здравствуйте, экспериментировал с вашей моделью, но лишь некоторые записи дают хороший результат. На Хабре вы писали, что пробовали так же обучать модель только для русского языка и она работала лучше, у вас не осталось натренерованной модели? Если да, не могли бы вы поделиться ей?

**Comment by vlomme** [comment]
Здравствуйте. Нет, не сохранилась. Но вы можете сами обучить. Причем можно взять двуязычную и дообучить синтезатор, что быстро

**Comment by arahisman** [comment]
Большое спасибо за ответ. Как я понимаю, есть ограничение на количество символов, ровно как и на длину спектрограммы, оно используется в тексте программы, но я не могу найти его определение, не подскажете, где можно его изменить?
Еще одна тонкость: При построении спектрограммы, чем дальше, тем менее выраженной она становится, если даже повторить одну и ту же фразу на повтор, она затухает.

**Comment by vlomme** [comment]
Модель обучалась на файлах до 7 секунд. Больше не влезало в видеокарту(
За это отвечает параметр max_mel_frames в synthesizer\hparams.py
Синтезировать можно любой длины, но так как на длинных файлах она не обучалось, то и работать будет хуже. На длину символов тоже ограничений нет.
Длинные тексты можно синтезировать,, разбив на отдельные строки. Тогда такой проблемы не будет

**Comment by arahisman** [comment]
Большое спасибо за ответ, вы очень помогли

пт, 27 мар. 2020 г., 17:22 Kramarenko Vladislav <notifications@github.com>:
