### ISSUE TITLE
Speech2Speech вместо Text2Speech

### ISSUE THREAD

**Issue by s1ddok** [vlomme/Multi-Tacotron-Voice-Cloning#12]
Спасибо больше за проект, я ищу какое-то быстрое решение для себя, которое могло бы делать voice style transfer (пародировать записанный голос по семплу), можно ли применить ваш синтезатор для этой задачи?

**Comment by vlomme** [comment]
Здравствуйте. К сожалению, нет. Во первых, нужен текст, во вторых, работает медленно, в третьих, качестве такое себе.

**Comment by s1ddok** [comment]
Понял, спасибо за ответ!
