### ISSUE TITLE
Unable to clone any voice other then the provided "ex.wav"

### ISSUE THREAD

**Issue by minghau** [vlomme/Multi-Tacotron-Voice-Cloning#2]
Hello, 
I tried using the demo with the pre-trained network. 
See the attached example. The output is just pure noise. 
Is there anything wrong with the voice sample i provided as input? 
I tried both male / female. 

Thanks, 
[orig_16.zip](https://github.com/vlomme/Multi-Tacotron-Voice-Cloning/files/3891084/orig_16.zip)

**Comment by vlomme** [comment]
Hello. I agree, the model does not work well. Not all voices produce sound. Need more data for training. I try other approaches. Try the original one-voice model, it works better https://github.com/CorentinJ/Real-Time-Voice-Cloning
