### ISSUE TITLE
Any Samples? 

### ISSUE THREAD

**Issue by Liujingxiu23** [vlomme/Multi-Tacotron-Voice-Cloning#3]
Hi I am doing similar work like yours, my datasets is "En + Chineses". 
I have tried the pretrained model offered by CorentinJ, and also finetune on the pretrained model, but i have not achieve good results till now. I am still training the encoder model now. And I wonder if you have some good results to share?

**Comment by FlyingDonkeyDev** [comment]
@Liujingxiu23 I think you have some examples published on the repo's home => https://soundcloud.com/fn5va3vghrkh/sets/multi-tacotron 😄
