### ISSUE TITLE
missed file "g2p/en.dic"

### ISSUE THREAD

**Issue by salisbury-espinosa** [vlomme/Multi-Tacotron-Voice-Cloning#4]
https://github.com/vlomme/Multi-Tacotron-Voice-Cloning/blob/master/g2p/train.py#L20

**Comment by vlomme** [comment]
https://drive.google.com/file/d/1tNElQSmpveVx0qyqKr1j5slfyM1HVifj/view

**Comment by Aziz87** [comment]
Спасибо
--
Отправлено из Mail.ru для Android суббота, 11 января 2020г., 22:37 +03:00 от Kramarenko Vladislav  notifications@github.com :
