### ISSUE TITLE
OOM Error by additional text to be spoken

### ISSUE THREAD

**Issue by ZirumAndBigBro** [vlomme/Multi-Tacotron-Voice-Cloning#5]
I have a problem inserting additional text to be spoken into the toolbox. The additional lines cause the vocoder to crash with out of memory error. Trying with the original code from CorentinJ and code from here I found that activating g2p in toolbox / __ init__ caused this error.
Apparently the g2p binds the resources that are important for other neural networks and does not release them when it has finished its task.
Can you fix that somehow?

Thank you

**Comment by vlomme** [comment]
fixed
