### ISSUE TITLE
WaveGlow

### ISSUE THREAD

**Issue by cnstntn-kndrtv** [vlomme/Multi-Tacotron-Voice-Cloning#7]
Is it possible to use WaveGlow?
And not to train your own model but use pretrained?

**Comment by vlomme** [comment]
Yes. You must replace the vocoder

**Comment by cnstntn-kndrtv** [comment]
Can you provide some example? 
Maybe we can create another branch.
Goal is to increase the quality of synthesised voice without long and expensive training. May be it would be helpful for you too.

**Comment by vlomme** [comment]
Sorry, but I don’t have the desire and time right now.
