### ISSUE TITLE
Не видит dataset

### ISSUE THREAD

**Issue by videoprice** [vlomme/Multi-Tacotron-Voice-Cloning#9]
Привет, у меня не видит dataset RU. LibriSpeech видит, а русский dataset не видит. Что делать? Спасибо

**Comment by vlomme** [comment]
У разных датасетов разная структура.
В synthesizer_preprocess_audio замените preprocess_sst на preprocess_librispeech.
Под свой датасет можете настроить \synthesizer\preprocess.py

**Comment by videoprice** [comment]
Спасибо за помощь, но ничего не выходит, не видит toolbox хоть убей:( Я хочу настроить dataset под RUSLAN https://ruslan-corpus.github.io/
Не покажете, как будет выглядить \synthesizer\preprocess.py под этот конкретный dataset
Огромное спасибо Владислав

**Comment by vlomme** [comment]
toolbox нужен уже для использования. Какой там вообще смысл открывать весь датасет? Можно отдельные файлы. Но если очень надо, можно отредактировать toolbox/__init__.py
И я не правильно прочитал, для тренировки синтезатора голосом RUSLAN нужно в synthesizer_preprocess_audio заменить preprocess_sst на preprocess_book. И тогда а сам датасет поместить в папку book (по умолчанию). Если надо, настраивается сама обработка в \synthesizer\preprocess.py
